 function hola(){
try{

    console.log(45)

    console.log(49)
}
catch(err){
    console.log("ERROR");
}finally{
    console.log("Esto acabo");
}

}
hola();

